src/core/models/scorecardData.js, src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/Components/PreviewScorecardTable/Components/PreviewCustomCell.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableBody/Components/AverageCell.js, src/shared/Components/ScorecardCell/Components/LinkedCellSvg.js
Modified average calculations for linked indicators
=> fix(Average Row and Column): Improvements

i18n/en.pot, src/core/state/orgUnit.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableCellAnalysis/Components/ChartAnalysis/index.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableCellAnalysis/Components/DictionaryAnalysis/Module/TopBar/index.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableCellAnalysis/Components/DimensionsSelector/Components/LayoutSelector/index.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableCellAnalysis/Components/DimensionsSelector/Components/OrgUnitSelector.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableCellAnalysis/Components/DimensionsSelector/Components/PeriodSelector.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableCellAnalysis/Components/DimensionsSelector/Components/SelectionWrapper.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableCellAnalysis/index.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableCellAnalysis/state/data.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableCellAnalysis/state/orgUnit.js, src/modules/Main/Components/ScorecardView/Components/ScorecardViewHeader/index.js, src/shared/Components/Loaders/ModalLoader.js, src/shared/utils/orgUnit.js
- Fixed styling for the further analysis modal
- Modified selectors for
further analysis modal
- Fixed issues with org unit selection
=> fix(Table Cell Analysis): Improvements & Fixes

i18n/en.pot, package.json, src/App.css, src/core/constants/form.js, src/core/state/scorecard.js, src/core/state/user.js, src/core/state/validators.js, src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/Components/DataGroups/Components/DataGroup/index.js, src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/Components/PreviewScorecardTable/Components/PreviewCustomCell.js, src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/Components/PreviewScorecardTable/index.js, src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/index.js, src/modules/Main/Components/ScoreCardManagement/Components/General/Components/GeneralFormField.js, src/modules/Main/Components/ScoreCardManagement/index.js, src/modules/Main/Components/ScoreCardManagement/services/validator.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/hooks/useTableOrgUnits.js, src/shared/icons/ErrorIcon.js
- Fixing issues with preview tables having inconsitent
column
arrangements
=> fix(Preview Table): Fixes

src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableBody/Components/ChildOrgUnitRow.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableBody/Components/DataSourceRow.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableBody/Components/ParentOrgUnitRow.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableBody/index.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableHeader/Components/GroupsHeaderRow.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableHeader/Components/OrgUnitHeaderRow.js
- Implemented item number options
=> feat(Item Number Option): Implementation

src/core/constants/config.js, src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/Components/DataGroups/Components/DataSourceSelectorModal/index.js, src/modules/Main/Components/ScoreCardManagement/Components/General/Components/GeneralForm.js, src/shared/Components/DataSourceSelector/Components/DataSource/hooks/useDataSources.js, src/shared/Components/DataSourceSelector/Components/GroupSelector/hooks/useDataGroups.js, src/shared/Components/DataSourceSelector/index.js, src/shared/Components/DataSourceSelector/models/customFunctions.js, src/shared/Components/DataSourceSelector/models/dataSource.js, src/shared/Components/DataSourceSelector/models/nativeDataSource.js
- Refactored the implementation of custom functions on the data source
selector
- Fixed issues with custom function rules id, it is now in the
format `functionId`.`ruleId`
=> fix(Data Source Selector): Fixes, Refactors

src/App.css, src/core/state/router.js, src/core/state/scorecard.js, src/modules/Main/Components/ScoreCardManagement/index.js, src/modules/Main/Components/ScorecardList/Components/Cards/ScorecardGridCard.js, src/modules/Main/Components/ScorecardList/Components/Cards/ScorecardListCard.js, src/modules/Main/Components/ScorecardList/index.js, src/modules/Main/Components/ScorecardView/Components/ScorecardActions.js, src/modules/Main/Components/ScorecardView/Components/ScorecardViewHeader/hooks/useDownload.js, src/modules/Main/Components/ScorecardView/Components/ScorecardViewHeader/index.js, src/modules/Main/Components/ScorecardView/Components/ScorecardViewHeader/services/download.js, src/modules/Main/Components/ScorecardView/index.js, src/shared/hooks/datastore/useScorecard.js
=> fix(Download ): Fixes

src/shared/hooks/datastore/useScorecard.js
Fixed issues with scorecard id is reused for consecutive scorecards additions
=> test(Add Scorecard): Fixes

src/modules/Main/Components/ScoreCardManagement/Components/Access/index.js, src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/Components/DataGroups/Components/DataGroup/Components/LinkingContainer.js, src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/Components/DataGroups/Components/DataGroup/index.js, src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/Components/DataGroups/Components/DataSourceSelectorModal/index.js, src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/DataGroupArea.js, src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/index.js, src/modules/Main/Components/ScoreCardManagement/Components/HighlightedIndicators/Table/index.js, src/modules/Main/Components/ScoreCardManagement/Components/HighlightedIndicators/index.js, src/modules/Main/Components/ScoreCardManagement/Components/Options/index.js, src/modules/Main/Components/ScoreCardManagement/ScorecardManagement.module.css, src/modules/Main/Components/ScoreCardManagement/index.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableCellAnalysis/Components/DictionaryAnalysis/Module/TopBar/Components/DataSourceSelector.js
- Set the data configuration and highlighted indicator areas to
have
their own scroll to remove issues with having to scroll
while
configuring an indicator
Closes #411
=> fix(Data configuration area): Fixes

src/core/state/scorecard.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableDataContainer/Components/DataCells.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableDataContainer/index.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/index.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/utils/index.js
- Limited arrow appearance to only if difference between previous and
current value is above or equal to the effective period
Closes #414
=> fix(Effective Gap): Fixes

src/modules/Main/Components/ScorecardView/Components/ScorecardActions.js, src/modules/Main/Components/ScorecardView/Components/ScorecardViewHeader/hooks/useDownload.js, src/modules/Main/Components/ScorecardView/index.js, src/shared/Components/Loaders/FullPageLoader.js
- Fixed issues with change in period or org unit or refreshing causes
the loading indicator to load all the page instead of just the scorecard
Closes #412
=> fix(Period Selection Loading): Fixes

src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/Components/DataGroups/Components/DataGroup/index.js, src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/Components/DataGroups/index.js
- Fixed issues with data configuration expands not working as expected
=> fix(Data Configuration): Fixes

i18n/en.pot, package.json, src/core/state/scorecard.js, src/modules/Main/Components/ScoreCardManagement/Components/General/Components/GeneralForm.js, src/modules/Main/Components/ScoreCardManagement/Components/General/Components/GeneralFormField.js, src/modules/Main/Components/ScoreCardManagement/Components/General/Components/LegendDefinitionFormField.js, src/modules/Main/Components/ScoreCardManagement/Components/General/utils/utils.js, src/modules/Main/Components/ScoreCardManagement/index.js, yarn.lock
- Implemented reset of legends whenever a definition is added or removed
=> fix(Legend Definitions): Fixes

package.json, yarn.lock
- Updated @dhis2/ui & @dhis2/app-runtime
=> chore(Dependencies): Updates

i18n/en.pot, src/core/state/scorecard.js, src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/Components/DataGroups/Components/DataGroup/index.js, src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/Components/DataGroups/index.js, src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/hooks/useDataGroupManage.js, src/modules/Main/Components/ScoreCardManagement/hooks/useScorecardManage.js, src/modules/Main/Components/ScoreCardManagement/hooks/useScorecardManagerNavigate.js, src/modules/Main/Components/ScoreCardManagement/index.js, src/modules/Main/Components/ScoreCardManagement/state/pages.js, src/shared/hooks/datastore/useScorecard.js, src/shared/hooks/datastore/useScorecardsSummary.js, yarn.lock
- Implemented save and continue feature
=> feat(configuration): save and continue

src/core/state/orgUnit.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableBody/index.js, yarn.lock
- Limited drill down for org units on the lowest level
Fixes #510 
=> fix(Scorecard Table): Fixes

package.json, src/App.css, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableBody/Components/ParentOrgUnitRow.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableBody/index.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/scorecardTable.module.css, src/modules/Main/Components/ScorecardView/index.js
- Fixed issues with download for multiple pages
Fixes #516 
=> feat(Download): Fixes

src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableCellAnalysis/Components/TableAnalysis/Components/table-item/table-item.component.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableCellAnalysis/Components/TableAnalysis/index.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableCellAnalysis/index.js
- Fixed styling issues with further analysis modal
=> fix(Further Cell Analysis): Styling

src/core/models/scorecardData.js, src/core/state/scorecard.js, src/modules/Main/Components/ScorecardView/Components/ScorecardActions.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableBody/index.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableDataContainer/index.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/index.js
- Changed implementation for refresh button to reset org unit and period.
=> Bugfix/issue #546

src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/Components/DataGroups/index.js, src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/DataGroupArea.js
- Modified search indicator algorithm on the `Data configuration` page
- Fixes and improvements on search indicator feature
Fixes #542
=> Bugfix/issue #542

package.json, src/modules/Main/Components/ScorecardView/Components/ScorecardLegendsView/ScorecardLegendsView.module.css, src/modules/Main/Components/ScorecardView/Components/ScorecardLegendsView/index.js, yarn.lock
- Fixed sytling issues with the `Legend Definitions` view on the scorecard view
Fixes #545
=> Bugfix/issue #545

src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableBody/Components/ChildOrgUnitRow.js
- Implemented expanding when user clicks on organisation unit name or
number
Fixes #549 
=> feat(Scorecard View): Table Rows

src/core/state/scorecard.js, src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/DataGroupArea.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableHeader/Components/GroupsHeaderRow.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableHeader/Components/HoldersHeaderRow.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableHeader/Components/OrgUnitHeaderRow.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableHeader/Components/PeriodHeaderRow.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/hooks/useTableConfig.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/hooks/useTableDataSources.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/hooks/useTableOrgUnits.js, src/modules/Main/Components/ScorecardView/index.js
- Refactored sort state to `atomFamily` with the respective orgUnits to allow independent sorting of each table. 
- Fixed issues with nested tables value and name sorting
Fixes #547
=> Bugfix/issue #547

src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableHeader/Components/GroupsHeaderRow.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableHeader/Components/HoldersHeaderRow.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableHeader/Components/OrgUnitHeaderCells.js
- Implemented condition that hides the group name if there is only one
group configured
Fixes #548 
=> feat(Scorecard Table): Group name hide for single groups

package.json, yarn.lock
- Updated @hisptz/react-ui dependency to solve issues with legend
definition field styles
Fixes #538
=> chore(Dependencies): Update

src/App.css, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableCellAnalysis/Components/ChartAnalysis/index.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableCellAnalysis/Components/DictionaryAnalysis/Module/TopBar/Components/DataSourceSelector.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableCellAnalysis/Components/DictionaryAnalysis/index.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableCellAnalysis/Components/TableAnalysis/index.js, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableCellAnalysis/TableCellAnalysis.module.css, src/modules/Main/Components/ScorecardView/Components/ScorecardTable/Components/TableCellAnalysis/index.js
- Implemented data source type search in dictionary
- Improved styling
for further cell view
Fixes #577 
=> fix(Dictionary): Fixes

src/modules/Main/Components/ScorecardView/Components/SpecificTargetsLibrary/index.js
- Fixed issues with headers of empty specific targets type appearing
=> fix(Scorecard PDF Download): Download title

src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/Components/DataGroups/Components/DataSourceConfiguration/Components/TargetsArea/components/LegendsField.js, src/shared/Components/CustomForm/components/DataSourceConfigurationForm/Components/TargetsField.js
- Added automatic assignment of adjacent values for legend min and max
values configuration
=> feat(Legend configuration): Implementation

apps/app/src/App.js, shared/components/src/ScorecardView/components/ScorecardTable/Components/TableBody/index.js, shared/components/src/ScorecardView/components/ScorecardTable/Components/TableHeader/Components/OrgUnitHeaderCells.js, shared/components/src/ScorecardView/components/ScorecardTable/hooks/useTableConfig.js, shared/components/src/ScorecardView/components/ScorecardTable/hooks/useTableDataSources.js, shared/components/src/ScorecardView/components/ScorecardTable/hooks/useTableOrgUnits.js, shared/components/src/ScorecardView/components/ScorecardTable/index.js, shared/components/src/ScorecardView/index.js, shared/hooks/src/useOrganisationUnits.js, shared/state/src/orgUnit.js, shared/state/src/scorecard.js
- Fixed issues incorrect payload for searched organisation unit
- Fixed issues with expanding while searching brings incorrect org Units
- Fixed issues with collapsing expansion clears search keyword 
- Fixed issues with searching causes whole table to reload
- Fixed issues with app getting stuck on searching data
=> Bugfix: Scorecard table search

apps/app/src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/Components/DataGroups/Components/DataSourceConfiguration/Components/OrgUnitSpecificTargetsModal/index.js, apps/app/src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/Components/DataGroups/Components/DataSourceConfiguration/Components/PeriodSpecificTargetsModal/index.js, apps/app/src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/Components/DataGroups/Components/DataSourceConfiguration/Components/TargetsArea/components/LegendsField.js, apps/app/src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/Components/DataGroups/Components/DataSourceConfiguration/Components/TargetsArea/components/LevelTargetsField.js, apps/app/src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/Components/DataGroups/Components/DataSourceConfiguration/Components/TargetsArea/components/TargetsField.js, apps/app/src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/Components/DataGroups/Components/DataSourceConfiguration/Components/TargetsArea/index.js
- Fixed an issue with auto assignment of adjacent legends misbehaving when highIsGood option is set to false
=> fix(legends config): Fixes

apps/app/src/modules/Main/Components/ScoreCardManagement/Components/DataConfiguration/hooks/useDataGroupManage.js, apps/app/src/modules/Main/Components/ScoreCardManagement/Components/DataSourceConfigurationForm/index.js, shared/components/src/ScorecardView/components/ScorecardTable/Components/TableCellAnalysis/Components/DictionaryAnalysis/Module/TopBar/Components/DataSourceSelector.js, shared/utils/src/dataSource.js, shared/utils/src/index.js, shared/utils/src/migrate.js
- Fixed issues with data source names not appearing for data sources that have been migrated
=> fix(data source name): Fixes
